
#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2020  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------


default:

exe:
	chmod +x *.sh *.pl

clean:
	-rm -f check.log check_orig.log aux.log copy.log

cleanall: clean

